[package]
name = "noisefunge"
version = "0.1.0"
authors = ["Rev. Johnny Healey <rev.null@gmail.com>"]
edition = "2018"

[lib]
name = "noisefunge"
path = "src/lib/lib.rs"

[[bin]]
name = "funged"
path = "src/funged/main.rs"

[dependencies]
jack = "0.6"
pancurses = "~0.16"
config = "~0.10"
clap = "~2.33"
rand = "~0.7"

