[package]
name = "noisefunge"
version = "0.1.0"
authors = ["Rev. Johnny Healey <rev.null@gmail.com>"]
edition = "2018"

[lib]
name = "noisefunge"
path = "src/lib/lib.rs"

[[bin]]
name = "funged"
path = "src/funged/main.rs"

[dependencies]
rand = "0.7"
jack = "0.6"
arr_macro = "0.1.3"
crossbeam-channel = "0.4.2"
pancurses = "0.16"
config = "0.9"
clap = "2.33"
simple-server = "0.4.0"
http = "0.1"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }

