
host = "0.0.0.0"
port = 1312

beats_in = "jack_midi_clock"
period = 6

[out.p1]
connect = "Qsynth1"
starting = 0

[out.p2]
connect = "Qsynth2"
starting = 16

[out.p3]
connect = "Qsynth3"
starting = 32

[out.p4]
connect = "Qsynth4"
starting = 48

[out.p5]
connect = "Qsynth5"
starting = 64

[channel.0]
program = 0

[channel.1]
program = 0
note_filter = "solo"

[channel.2]
program = 8
note_filter = "random:4:4:6"

[channel.3]
program = 12
note_filter = "up:2:2:1"

[channel.4]
program = 13
note_filter = "down:1:3:1"

[channel.5]
program = 14
note_filter = "bi:2"

[channel.18]
bank = 0
program = 0
