
host = "0.0.0.0"
port = 1312

beats_in = "jack_midi_clock"
period = 6

[out.p1]
connect = "Qsynth1"
starting = 0

[out.p2]
connect = "Qsynth2"
starting = 16

[out.p3]
connect = "Qsynth3"
starting = 32

[out.p4]
connect = "Qsynth4"
starting = 48

[out.p5]
connect = "Qsynth5"
starting = 64

[channel.0]
program = 0

[channel.1]
program = 5

