
host = "0.0.0.0"
port = 1312

beats_in = "jack_midi_clock:mclk_out"
period = 6

log_level = "DEBUG"

[subprocess.clock]
command = ["jack_midi_clock", "-b", "132"]

[subprocess.dump]
command = ["jack_midi_dump"]
stdout = "/tmp/midi.dump"

[out.p1]
connect = ["Qsynth1:midi_00", "midi-monitor:input"]
starting = 0

[out.p2]
connect = "Qsynth2:midi_00"
starting = 16

[out.p3]
connect = "Qsynth3:midi_00"
starting = 32

[out.p4]
connect = "Qsynth4:midi_00"
starting = 48

[out.p5]
connect = "Qsynth5:midi_00"
starting = 64

[channel.0]
program = 0

[channel.1]
program = 0
note_filter = "solo"

[channel.2]
program = 8
note_filter = "random:4:4:6"

[channel.3]
program = 12
note_filter = "up:2:2:1"

[channel.4]
program = 13
note_filter = "down:1:3:1"

[channel.5]
program = 14
note_filter = "bi:2"

[channel.6]
bank = 128
program = 25
note_filter = "bi:2"

[channel.18]
bank = 0
program = 0
